# Builds an image to run local tests
# Build using e.g. `podman build -t qos-test . -f Dockerfile.run_tests`
# Execute tests with `podman run --rm -it qos-test:latest`

FROM registry.gitlab.com/qubesos/docker-images/qubesos-ci:latest

RUN sudo dnf install -y \
    openssl \
    python3-rpm \
    sequoia-sqv \
    python3-xlib \
    libnotify \
    zstd \
    xorg-x11-server-Xvfb \
    && sudo dnf clean all
RUN sudo dnf install -y --enablerepo=qubes-host-r4.3-current-testing scrypt

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /workspace
COPY . /workspace
RUN sudo chown -R gitlab-runner:gitlab-runner /workspace

USER gitlab-runner
ENV USER=gitlab-runner
ENV ENABLE_SLOW_TESTS=1
CMD xvfb-run uv run python -m unittest discover -s qubesadmin/tests -p '*.py' -v
