#!/bin/sh

: "${PYTHON:=python}"
: "${TESTPYTHONPATH:=test-packages}"

PYTHONPATH="${TESTPYTHONPATH}:${PYTHONPATH}"
export PYTHONPATH

"${PYTHON}" setup.py egg_info --egg-base "${TESTPYTHONPATH}"
"${PYTHON}" -m coverage run --rcfile=ci/coveragerc -m unittest discover -p '*.py' -v "$@"
