#!/bin/sh

: "${PYTHON:=python3}"
: "${ROOTDIR:=.}"
: "${TESTPYTHONPATH:=$ROOTDIR/test-packages}"

PYTHONPATH="${TESTPYTHONPATH}:${PYTHONPATH}"
export PYTHONPATH

[ -r version ] || ln -s ${ROOTDIR}/version ./
"${PYTHON}" -m pip install -e . --no-deps

"${PYTHON}" -m coverage run --rcfile=$ROOTDIR/ci/coveragerc -m unittest discover -s qubesadmin/tests -p '*.py' -v "$@"
