#!/bin/bash

print_usage() {
cat >&2 <<USAGE
Usage: $0 vmname
Starts given VM and runs its associated GUI daemon. Used as X session for the
GUI domain.
USAGE
}

if [ $# -lt 1 ] ; then
    print_usage
    exit 1
fi

qvm-start sys-gui
exec qvm-start-daemon --watch --exit --gui-allow-fullscreen "$1"
